### ISSUE TITLE
Refactor cookie handling using some other package

### ISSUE THREAD

**Issue by benbart** [asfadmin/rain-api-core#162]
https://github.com/asfadmin/rain-api-core/blob/8f2ad2cf323231920ad5cf42f293c580d1cee479/rain_api_core/view_util.py#L136

maybe: 
https://docs.python.org/3.8/library/http.cookies.html

**Comment by reweeden** [comment]
Parsing cookies is non-trivial and there are some cases where the current implementation (simple string splits) does not get the right values. For example:

```python3
get_cookies({"cookie": "key=YXNkZg=="})
# returns {"key": "YXNkZg"}
```

Correct handling of equals signs is important because cookies can hold arbitrary base64 encoded values (`YXNkZg==` is the base64 encoded string `asdf`) which may be done when the app needs to be able to handle arbitrary binary data in cookies.
